"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { Printer, FileDown, Share2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { renderToStaticMarkup } from "react-dom/server";
import UnifiedDoorcard, { DoorcardLite } from "./UnifiedDoorcard";

interface DoorcardActionsProps {
  doorcard: DoorcardLite;
  containerId?: string;
}

export function DoorcardActions({
  doorcard,
  containerId = "doorcard-schedule",
}: DoorcardActionsProps) {
  const { toast } = useToast();
  const [htmlExport, setHtmlExport] = useState("");

  async function handlePdf() {
    const target = document.getElementById(containerId);
    if (!target) return;
    const [{ default: html2canvas }, { default: jsPDF }] = await Promise.all([
      import("html2canvas"),
      import("jspdf"),
    ]);
    const canvas = await html2canvas(target, {
      scale: 2,
      backgroundColor: "#fff",
    });
    const imgWidth = 210;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    const pdf = new jsPDF({
      orientation: imgHeight > imgWidth ? "portrait" : "landscape",
      unit: "mm",
    });
    pdf.addImage(
      canvas.toDataURL("image/png"),
      "PNG",
      0,
      0,
      imgWidth,
      imgHeight
    );
    pdf.save(`${doorcard.name || "doorcard"}-schedule.pdf`);
  }

  function buildHtml() {
    // Render server component markup client-side for copy
    const markup = renderToStaticMarkup(
      <UnifiedDoorcard doorcard={doorcard} containerId="export-ignore" />
    );
    setHtmlExport(`<!-- Generated by Doorcard App -->\n${markup}`);
  }

  function copyHtml() {
    navigator.clipboard
      .writeText(htmlExport)
      .then(() =>
        toast({ title: "Copied", description: "HTML copied to clipboard." })
      )
      .catch(() =>
        toast({
          variant: "destructive",
          title: "Error",
          description: "Clipboard write failed.",
        })
      );
  }

  function share() {
    if (navigator.share) {
      navigator.share({
        title: doorcard.doorcardName || "Faculty Doorcard",
        url: window.location.href,
      });
    } else {
      navigator.clipboard.writeText(window.location.href);
      toast({ title: "Copied", description: "Link copied to clipboard." });
    }
  }

  return (
    <div className="flex gap-2 print:hidden mb-4">
      <Button variant="outline" onClick={() => window.print()}>
        <Printer className="h-4 w-4 mr-1" /> Print
      </Button>
      <Button onClick={handlePdf}>
        <FileDown className="h-4 w-4 mr-1" /> PDF
      </Button>
      <Button variant="outline" onClick={share}>
        <Share2 className="h-4 w-4 mr-1" /> Share
      </Button>
      <Dialog onOpenChange={(o) => o && buildHtml()}>
        <DialogTrigger asChild>
          <Button>Export HTML</Button>
        </DialogTrigger>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Canvas HTML Export</DialogTitle>
          </DialogHeader>
          <Textarea
            readOnly
            value={htmlExport}
            className="min-h-[240px] font-mono text-xs"
          />
          <Button onClick={copyHtml}>Copy</Button>
        </DialogContent>
      </Dialog>
    </div>
  );
}
