"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { Printer, FileDown, Share2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { renderToStaticMarkup } from "react-dom/server";
import { DoorcardLite } from "./UnifiedDoorcard";
import { PrintOptimizedDoorcard } from "./PrintOptimizedDoorcard";
import { SimplePDF } from "./pdf/SimplePDF";
import { analytics } from "@/lib/analytics";

interface DoorcardActionsProps {
  doorcard: DoorcardLite;
  doorcardId?: string; // Add doorcardId for analytics tracking
  containerId?: string;
}

export function DoorcardActions({
  doorcard,
  doorcardId,
  containerId = "doorcard-schedule",
}: DoorcardActionsProps) {
  const { toast } = useToast();
  const [htmlExport, setHtmlExport] = useState("");

  async function handlePdf() {
    // Track PDF download event
    if (doorcardId) {
      analytics.trackPrint(doorcardId, "download");
    }
    
    // Create a temporary container with the print-optimized doorcard
    const tempContainer = document.createElement('div');
    tempContainer.style.position = 'absolute';
    tempContainer.style.left = '-9999px';
    tempContainer.style.width = '8.5in';
    tempContainer.style.height = '11in';
    tempContainer.style.backgroundColor = 'white';
    tempContainer.style.padding = '0.5in';
    
    // Render the print-optimized version
    const printContent = renderToStaticMarkup(
      <PrintOptimizedDoorcard doorcard={doorcard} containerId="pdf-export" />
    );
    tempContainer.innerHTML = printContent;
    document.body.appendChild(tempContainer);
    
    try {
      const [{ default: html2canvas }, { default: jsPDF }] = await Promise.all([
        import("html2canvas"),
        import("jspdf"),
      ]);
      
      const canvas = await html2canvas(tempContainer, {
        scale: 2,
        backgroundColor: "#fff",
        width: 816, // 8.5in at 96 DPI
        height: 1056, // 11in at 96 DPI
        useCORS: true,
      });
      
      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "letter",
      });
      
      // Fit to single page
      const pdfWidth = 210; // A4 width in mm
      const pdfHeight = 297; // A4 height in mm
      
      pdf.addImage(
        canvas.toDataURL("image/png"),
        "PNG",
        0,
        0,
        pdfWidth,
        pdfHeight
      );
      
      pdf.save(`${doorcard.name || "doorcard"}-schedule.pdf`);
    } finally {
      // Clean up
      document.body.removeChild(tempContainer);
    }
  }

  function buildHtml() {
    // Render print-optimized version for export
    const markup = renderToStaticMarkup(
      <PrintOptimizedDoorcard doorcard={doorcard} containerId="export-ignore" />
    );
    setHtmlExport(`<!-- Generated by Doorcard App - Print Optimized -->\n${markup}`);
  }

  function copyHtml() {
    navigator.clipboard
      .writeText(htmlExport)
      .then(() =>
        toast({ title: "Copied", description: "HTML copied to clipboard." })
      )
      .catch(() =>
        toast({
          variant: "destructive",
          title: "Error",
          description: "Clipboard write failed.",
        })
      );
  }

  function share() {
    // Track share event
    if (doorcardId) {
      const method = navigator.share ? "native" : "clipboard";
      analytics.trackShare(doorcardId, method);
    }
    
    if (navigator.share) {
      navigator.share({
        title: doorcard.doorcardName || "Faculty Doorcard",
        url: window.location.href,
      });
    } else {
      navigator.clipboard.writeText(window.location.href);
      toast({ title: "Copied", description: "Link copied to clipboard." });
    }
  }

  return (
    <div className="flex gap-2 print:hidden mb-4">
      <Button variant="outline" onClick={() => {
        if (doorcardId) {
          analytics.trackPrint(doorcardId, "preview");
        }
        window.print();
      }}>
        <Printer className="h-4 w-4 mr-1" /> Print
      </Button>
      <SimplePDF 
        doorcard={doorcard} 
        doorcardId={doorcardId}
        onDownload={() => {
          if (doorcardId) {
            analytics.trackPrint(doorcardId, "download");
          }
        }}
      />
      <Button variant="outline" onClick={share}>
        <Share2 className="h-4 w-4 mr-1" /> Share
      </Button>
      <Dialog onOpenChange={(o) => o && buildHtml()}>
        <DialogTrigger asChild>
          <Button>Export HTML</Button>
        </DialogTrigger>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Canvas HTML Export</DialogTitle>
          </DialogHeader>
          <Textarea
            readOnly
            value={htmlExport}
            className="min-h-[240px] font-mono text-xs"
          />
          <Button onClick={copyHtml}>Copy</Button>
        </DialogContent>
      </Dialog>
    </div>
  );
}
