export const createDoorcardDraft = jest.fn()
export const updateDoorcardDraft = jest.fn()
export const deleteDoorcardDraft = jest.fn()
export const updateBasicInfo = jest.fn()
export const saveDoorcard = jest.fn()